name: fp-exam
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --privileged
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: dependencies
        run: |
          apt-get update
          apt-get install texlive-xetex pandoc -y
      - name: setup
        uses: actions/checkout@v3
      - name: build
        run: |
          bash build.sh
          cd sources && zip -9 fp-exam.zip *.pdf && zip --test fp-exam.zip
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sources/fp-exam.zip
          asset_name: fp-exam.zip
          asset_content_type: application/pdf
