name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --privileged
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: dependencies
        run: |
          apt-get update
          apt-get install texlive-xetex pandoc -y
      - name: setup
        uses: actions/checkout@v4
      - name: build
        run: bash build.sh
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: exam-files
          path: sources/*.pdf
          if-no-files-found: error
